ALTER DATABASE Tests 
ADD FILE
(
NAME = p_2015,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\p_2015.ndf'
)
TO FILEGROUP FG2015
GO
ALTER DATABASE Tests 
ADD FILE
(
NAME = p_2016,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\p_2016.ndf'
)
TO FILEGROUP FG2016
GO
ALTER DATABASE Tests 
ADD FILE
(
NAME = p_2017,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\p_2017.ndf'
)
TO FILEGROUP FG2017
GO
ALTER DATABASE Tests
ADD FILE
(
NAME = p_2018,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\p_2018.ndf'
)
TO FILEGROUP FG2018
GO
ALTER DATABASE Tests
ADD FILE
(
NAME = p_2019,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\p_2019.ndf'
)
TO FILEGROUP FG2019
GO
ALTER DATABASE Tests 
ADD FILE
(
NAME = p_2020,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\p_2020.ndf'
)
TO FILEGROUP FG2020
GO
ALTER DATABASE Tests 
ADD FILE
(
NAME = p_2021,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\p_2021.ndf'
)
TO FILEGROUP FG2021
GO
ALTER DATABASE Tests 
ADD FILE
(
NAME = p_2022,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\p_2022.ndf'
)
TO FILEGROUP FG2022
GO
ALTER DATABASE Tests 
ADD FILE
(
NAME = p_2023,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\p_2023.ndf'
)
TO FILEGROUP FG2023
GO
ALTER DATABASE Tests 
ADD FILE
(
NAME = p_2024,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\p_2024.ndf'
)
TO FILEGROUP FG2024
GO
ALTER DATABASE Tests 
ADD FILE
(
NAME = p_2025,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\p_2025.ndf'
)
TO FILEGROUP FG2025